import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import { Toaster } from "sonner";
import { UserProfileProvider } from "@/context/UserProfile";
import { CartContextProvider } from "@/context/CartProvider";

const popLight = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "RedSeam Clothing",
  description: "Generated by Redberry",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${popLight.className} antialiased px-[100px]`}>
        <UserProfileProvider>
          <CartContextProvider>
            <Header />
            {children}
          </CartContextProvider>
        </UserProfileProvider>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
